name = medival_combat
title = Medival Combat
description = Adds many medival weapons to Minetest, all with different properties.
depends = mobs
min_minetest_version = 5.13
supported_games = minetest_game
unsupported_games = exile, extra_ordinance, pmb_core, mineclonia, mineclone2, nodecore